CXX = g++
CXXFLAGS = -std=c++11 -Wall
OBJS = capitalize-vowels-main.cc capitalize-vowels.cc

capitalize-vowels: $(OBJS)
	g++ -o capitalize-vowels $(OBJS) 
clean: 
	rm -f capitalize-vowels
run:
	./capitalize-vowels
